version: '2'

services:
  app:
    build: .
    volumes:
      - "./:/app"
    env_file:
      - ".env-sample"
    environment:
      # CI envs
      CI:
      RAILS_ENV:
      # CI envs For Knapsack
      BUILDKITE_PARALLEL_JOB:
      BUILDKITE_PARALLEL_JOB_COUNT:
      BUILDKITE_COMMIT:
      BUILDKITE_BRANCH:
      BUILDKITE_REPO:
      BUILDKITE_BUILD_ID:
      BUILDKITE_BUILD_NUMBER:
    ports:
      - "5000:5000"
